// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQJleBE5BYD28eyXLieDLVjtWJBxCvm9k',
    appId: '1:314951118059:web:ea3cb3e25e1ed7613ae2ae',
    messagingSenderId: '314951118059',
    projectId: 'todolist-bb59f',
    authDomain: 'todolist-bb59f.firebaseapp.com',
    storageBucket: 'todolist-bb59f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCje9VeRsKy2rUulAalqP7QAPxa0uWmrhk',
    appId: '1:314951118059:android:5a1d7e6622b3108e3ae2ae',
    messagingSenderId: '314951118059',
    projectId: 'todolist-bb59f',
    storageBucket: 'todolist-bb59f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvBzQ6x-6qYnsnETA9RYecy48TUITj7PE',
    appId: '1:314951118059:ios:074600d58c1c79c63ae2ae',
    messagingSenderId: '314951118059',
    projectId: 'todolist-bb59f',
    storageBucket: 'todolist-bb59f.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvBzQ6x-6qYnsnETA9RYecy48TUITj7PE',
    appId: '1:314951118059:ios:1e4c3c0d5ac15a223ae2ae',
    messagingSenderId: '314951118059',
    projectId: 'todolist-bb59f',
    storageBucket: 'todolist-bb59f.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
